package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AtividadeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtividadeAllPropertiesEquals(Atividade expected, Atividade actual) {
        assertAtividadeAutoGeneratedPropertiesEquals(expected, actual);
        assertAtividadeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtividadeAllUpdatablePropertiesEquals(Atividade expected, Atividade actual) {
        assertAtividadeUpdatableFieldsEquals(expected, actual);
        assertAtividadeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtividadeAutoGeneratedPropertiesEquals(Atividade expected, Atividade actual) {
        assertThat(actual)
            .as("Verify Atividade auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtividadeUpdatableFieldsEquals(Atividade expected, Atividade actual) {
        assertThat(actual)
            .as("Verify Atividade relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getModo()).as("check modo").isEqualTo(expected.getModo()))
            .satisfies(a -> assertThat(a.getDataInicio()).as("check dataInicio").isEqualTo(expected.getDataInicio()))
            .satisfies(a -> assertThat(a.getDataFim()).as("check dataFim").isEqualTo(expected.getDataFim()))
            .satisfies(a -> assertThat(a.getTempoLimite()).as("check tempoLimite").isEqualTo(expected.getTempoLimite()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtividadeUpdatableRelationshipsEquals(Atividade expected, Atividade actual) {
        assertThat(actual)
            .as("Verify Atividade relationships")
            .satisfies(a -> assertThat(a.getSala()).as("check sala").isEqualTo(expected.getSala()))
            .satisfies(a -> assertThat(a.getLista()).as("check lista").isEqualTo(expected.getLista()));
    }
}
