package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConquistaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConquistaAllPropertiesEquals(Conquista expected, Conquista actual) {
        assertConquistaAutoGeneratedPropertiesEquals(expected, actual);
        assertConquistaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConquistaAllUpdatablePropertiesEquals(Conquista expected, Conquista actual) {
        assertConquistaUpdatableFieldsEquals(expected, actual);
        assertConquistaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConquistaAutoGeneratedPropertiesEquals(Conquista expected, Conquista actual) {
        assertThat(actual)
            .as("Verify Conquista auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConquistaUpdatableFieldsEquals(Conquista expected, Conquista actual) {
        assertThat(actual)
            .as("Verify Conquista relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getXpRecompensa()).as("check xpRecompensa").isEqualTo(expected.getXpRecompensa()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConquistaUpdatableRelationshipsEquals(Conquista expected, Conquista actual) {
        // empty method
    }
}
