package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ErroOrtograficoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertErroOrtograficoAllPropertiesEquals(ErroOrtografico expected, ErroOrtografico actual) {
        assertErroOrtograficoAutoGeneratedPropertiesEquals(expected, actual);
        assertErroOrtograficoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertErroOrtograficoAllUpdatablePropertiesEquals(ErroOrtografico expected, ErroOrtografico actual) {
        assertErroOrtograficoUpdatableFieldsEquals(expected, actual);
        assertErroOrtograficoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertErroOrtograficoAutoGeneratedPropertiesEquals(ErroOrtografico expected, ErroOrtografico actual) {
        assertThat(actual)
            .as("Verify ErroOrtografico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertErroOrtograficoUpdatableFieldsEquals(ErroOrtografico expected, ErroOrtografico actual) {
        assertThat(actual)
            .as("Verify ErroOrtografico relevant properties")
            .satisfies(a -> assertThat(a.getTipoErro()).as("check tipoErro").isEqualTo(expected.getTipoErro()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertErroOrtograficoUpdatableRelationshipsEquals(ErroOrtografico expected, ErroOrtografico actual) {
        assertThat(actual)
            .as("Verify ErroOrtografico relationships")
            .satisfies(a -> assertThat(a.getResposta()).as("check resposta").isEqualTo(expected.getResposta()));
    }
}
