package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ListaPalavrasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaPalavrasAllPropertiesEquals(ListaPalavras expected, ListaPalavras actual) {
        assertListaPalavrasAutoGeneratedPropertiesEquals(expected, actual);
        assertListaPalavrasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaPalavrasAllUpdatablePropertiesEquals(ListaPalavras expected, ListaPalavras actual) {
        assertListaPalavrasUpdatableFieldsEquals(expected, actual);
        assertListaPalavrasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaPalavrasAutoGeneratedPropertiesEquals(ListaPalavras expected, ListaPalavras actual) {
        assertThat(actual)
            .as("Verify ListaPalavras auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaPalavrasUpdatableFieldsEquals(ListaPalavras expected, ListaPalavras actual) {
        assertThat(actual)
            .as("Verify ListaPalavras relevant properties")
            .satisfies(a -> assertThat(a.getNomeLista()).as("check nomeLista").isEqualTo(expected.getNomeLista()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaPalavrasUpdatableRelationshipsEquals(ListaPalavras expected, ListaPalavras actual) {
        assertThat(actual)
            .as("Verify ListaPalavras relationships")
            .satisfies(a -> assertThat(a.getPalavras()).as("check palavras").isEqualTo(expected.getPalavras()))
            .satisfies(a -> assertThat(a.getProfessor()).as("check professor").isEqualTo(expected.getProfessor()));
    }
}
