package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PalavraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPalavraAllPropertiesEquals(Palavra expected, Palavra actual) {
        assertPalavraAutoGeneratedPropertiesEquals(expected, actual);
        assertPalavraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPalavraAllUpdatablePropertiesEquals(Palavra expected, Palavra actual) {
        assertPalavraUpdatableFieldsEquals(expected, actual);
        assertPalavraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPalavraAutoGeneratedPropertiesEquals(Palavra expected, Palavra actual) {
        assertThat(actual)
            .as("Verify Palavra auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPalavraUpdatableFieldsEquals(Palavra expected, Palavra actual) {
        assertThat(actual)
            .as("Verify Palavra relevant properties")
            .satisfies(a -> assertThat(a.getTexto()).as("check texto").isEqualTo(expected.getTexto()))
            .satisfies(a -> assertThat(a.getDificuldade()).as("check dificuldade").isEqualTo(expected.getDificuldade()))
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()))
            .satisfies(a -> assertThat(a.getIdioma()).as("check idioma").isEqualTo(expected.getIdioma()))
            .satisfies(a -> assertThat(a.getPossuiAcento()).as("check possuiAcento").isEqualTo(expected.getPossuiAcento()))
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPalavraUpdatableRelationshipsEquals(Palavra expected, Palavra actual) {
        assertThat(actual)
            .as("Verify Palavra relationships")
            .satisfies(a -> assertThat(a.getCriador()).as("check criador").isEqualTo(expected.getCriador()))
            .satisfies(a -> assertThat(a.getListas()).as("check listas").isEqualTo(expected.getListas()));
    }
}
