package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RankingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingAllPropertiesEquals(Ranking expected, Ranking actual) {
        assertRankingAutoGeneratedPropertiesEquals(expected, actual);
        assertRankingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingAllUpdatablePropertiesEquals(Ranking expected, Ranking actual) {
        assertRankingUpdatableFieldsEquals(expected, actual);
        assertRankingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingAutoGeneratedPropertiesEquals(Ranking expected, Ranking actual) {
        assertThat(actual)
            .as("Verify Ranking auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingUpdatableFieldsEquals(Ranking expected, Ranking actual) {
        assertThat(actual)
            .as("Verify Ranking relevant properties")
            .satisfies(a -> assertThat(a.getPosicao()).as("check posicao").isEqualTo(expected.getPosicao()))
            .satisfies(a -> assertThat(a.getPontuacaoTotal()).as("check pontuacaoTotal").isEqualTo(expected.getPontuacaoTotal()))
            .satisfies(a -> assertThat(a.getUltimaAtualizacao()).as("check ultimaAtualizacao").isEqualTo(expected.getUltimaAtualizacao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingUpdatableRelationshipsEquals(Ranking expected, Ranking actual) {
        assertThat(actual)
            .as("Verify Ranking relationships")
            .satisfies(a -> assertThat(a.getSala()).as("check sala").isEqualTo(expected.getSala()))
            .satisfies(a -> assertThat(a.getAluno()).as("check aluno").isEqualTo(expected.getAluno()));
    }
}
