package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RespostaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespostaAllPropertiesEquals(Resposta expected, Resposta actual) {
        assertRespostaAutoGeneratedPropertiesEquals(expected, actual);
        assertRespostaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespostaAllUpdatablePropertiesEquals(Resposta expected, Resposta actual) {
        assertRespostaUpdatableFieldsEquals(expected, actual);
        assertRespostaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespostaAutoGeneratedPropertiesEquals(Resposta expected, Resposta actual) {
        assertThat(actual)
            .as("Verify Resposta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespostaUpdatableFieldsEquals(Resposta expected, Resposta actual) {
        assertThat(actual)
            .as("Verify Resposta relevant properties")
            .satisfies(a -> assertThat(a.getRespostaDigitada()).as("check respostaDigitada").isEqualTo(expected.getRespostaDigitada()))
            .satisfies(a -> assertThat(a.getCorreta()).as("check correta").isEqualTo(expected.getCorreta()))
            .satisfies(a -> assertThat(a.getTempoResposta()).as("check tempoResposta").isEqualTo(expected.getTempoResposta()))
            .satisfies(a -> assertThat(a.getPontuacao()).as("check pontuacao").isEqualTo(expected.getPontuacao()))
            .satisfies(a -> assertThat(a.getDataResposta()).as("check dataResposta").isEqualTo(expected.getDataResposta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespostaUpdatableRelationshipsEquals(Resposta expected, Resposta actual) {
        assertThat(actual)
            .as("Verify Resposta relationships")
            .satisfies(a -> assertThat(a.getAtividade()).as("check atividade").isEqualTo(expected.getAtividade()))
            .satisfies(a -> assertThat(a.getAluno()).as("check aluno").isEqualTo(expected.getAluno()))
            .satisfies(a -> assertThat(a.getPalavra()).as("check palavra").isEqualTo(expected.getPalavra()));
    }
}
