package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaAllPropertiesEquals(Sala expected, Sala actual) {
        assertSalaAutoGeneratedPropertiesEquals(expected, actual);
        assertSalaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaAllUpdatablePropertiesEquals(Sala expected, Sala actual) {
        assertSalaUpdatableFieldsEquals(expected, actual);
        assertSalaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaAutoGeneratedPropertiesEquals(Sala expected, Sala actual) {
        // A PK é o código (informado pelo cliente) — não há propriedades geradas pelo banco
        assertThat(actual)
            .as("Verify Sala primary key")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaUpdatableFieldsEquals(Sala expected, Sala actual) {
        assertThat(actual)
            .as("Verify Sala relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaUpdatableRelationshipsEquals(Sala expected, Sala actual) {
        assertThat(actual)
            .as("Verify Sala relationships")
            .satisfies(a -> assertThat(a.getProfessor()).as("check professor").isEqualTo(expected.getProfessor()))
            .satisfies(a -> assertThat(a.getAlunos()).as("check alunos").isEqualTo(expected.getAlunos()));
    }
}
