package br.com.digitado.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UsuarioConquistaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConquistaAllPropertiesEquals(UsuarioConquista expected, UsuarioConquista actual) {
        assertUsuarioConquistaAutoGeneratedPropertiesEquals(expected, actual);
        assertUsuarioConquistaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConquistaAllUpdatablePropertiesEquals(UsuarioConquista expected, UsuarioConquista actual) {
        assertUsuarioConquistaUpdatableFieldsEquals(expected, actual);
        assertUsuarioConquistaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConquistaAutoGeneratedPropertiesEquals(UsuarioConquista expected, UsuarioConquista actual) {
        assertThat(actual)
            .as("Verify UsuarioConquista auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConquistaUpdatableFieldsEquals(UsuarioConquista expected, UsuarioConquista actual) {
        assertThat(actual)
            .as("Verify UsuarioConquista relevant properties")
            .satisfies(a -> assertThat(a.getDataConquista()).as("check dataConquista").isEqualTo(expected.getDataConquista()))
            .satisfies(a -> assertThat(a.getProgresso()).as("check progresso").isEqualTo(expected.getProgresso()))
            .satisfies(a -> assertThat(a.getConcluida()).as("check concluida").isEqualTo(expected.getConcluida()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioConquistaUpdatableRelationshipsEquals(UsuarioConquista expected, UsuarioConquista actual) {
        assertThat(actual)
            .as("Verify UsuarioConquista relationships")
            .satisfies(a -> assertThat(a.getAluno()).as("check aluno").isEqualTo(expected.getAluno()))
            .satisfies(a -> assertThat(a.getConquista()).as("check conquista").isEqualTo(expected.getConquista()));
    }
}
